# Generated by Django 5.2.1 on 2025-06-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('acc_num', models.BigAutoField(default=1234567890, primary_key=True, serialize=False, unique=True)),
                ('phone', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('pin', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
            ],
        ),
    ]
