# Generated by Django 5.2.1 on 2025-07-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_acc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
