# Generated by Django 5.2.1 on 2025-07-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_account_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_num',
            field=models.BigAutoField(default=12345678912, primary_key=True, serialize=False, unique=True),
        ),
    ]
