# Generated by Django 5.2.1 on 2025-07-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_account_acc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_num',
            field=models.BigAutoField(default=12345678912, primary_key=True, serialize=False, unique=True),
        ),
    ]
